# Generated by Django 2.2.14 on 2020-08-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typs_list',
            name='tname',
            field=models.CharField(max_length=12, verbose_name='栏目分类名'),
        ),
        migrations.AlterModelTable(
            name='typs_list',
            table='Typs_List',
        ),
    ]
