# Generated by Django 2.2.14 on 2020-08-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200820_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obj_list',
            old_name='oname',
            new_name='tname',
        ),
    ]
