# Generated by Django 2.2.14 on 2020-08-20 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200820_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('url', models.CharField(max_length=512)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Obj_List')),
            ],
            options={
                'db_table': 'Article_List',
            },
        ),
    ]
