# Generated by Django 2.2.14 on 2020-08-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200820_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_list',
            name='is_delect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article_list',
            name='is_top',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='obj_list',
            name='is_delect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obj_list',
            name='is_top',
            field=models.IntegerField(default=0),
        ),
    ]
